# Generated by Django 6.0.3 on 2026-03-26 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_brand_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('specs', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spare', to='core.product')),
            ],
            options={
                'verbose_name': 'Battery',
                'verbose_name_plural': 'Battery',
            },
        ),
    ]
