# Generated by Django 6.0.3 on 2026-03-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('core', '0002_brand_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('interface', models.CharField(blank=True, choices=[('SAS', 'SAS'), ('SATA', 'SATA'), ('FC', 'FC'), ('SCSI', 'SCSI')], max_length=10, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_serial_no_1', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('port', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='core.product')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
