# Generated by Django 6.0.3 on 2026-04-24 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_controller_spare_controller'),
        ('core', '0003_alter_product_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('part_no_1', models.CharField(blank=True, max_length=100, null=True)),
                ('part_no_2', models.CharField(blank=True, max_length=100, null=True)),
                ('part_no_3', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('ram_type', models.CharField(blank=True, choices=[('ECC REGD', 'ECC Registered'), ('FB DIMM', 'FB DIMM'), ('ECC UDIMM', 'ECC UDIMM'), ('UDIMM', 'UDIMM'), ('RDIMM', 'RDIMM'), ('LRDIMM', 'LRDIMM')], max_length=20, null=True)),
                ('ddr_version', models.CharField(blank=True, max_length=20, null=True)),
                ('frequency', models.CharField(blank=True, max_length=30, null=True)),
                ('rank', models.CharField(blank=True, max_length=20, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='core.product')),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memory',
            },
        ),
    ]
