# Generated by Django 6.0.3 on 2026-04-24 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_memory'),
        ('core', '0003_alter_product_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('fibre_type', models.CharField(blank=True, choices=[('SMF', 'SMF - Single Mode Fibre'), ('MMF', 'MMF - Multi Mode Fibre')], max_length=10, null=True)),
                ('data_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sfp', to='core.product')),
            ],
            options={
                'verbose_name': 'SFP',
                'verbose_name_plural': 'SFPs',
            },
        ),
    ]
