# Generated by Django 6.0.3 on 2026-04-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_sfp'),
        ('core', '0003_alter_product_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('PAIR', 'Pair')], max_length=10, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('specs', models.CharField(blank=True, max_length=255, null=True)),
                ('supported_model', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='railkit', to='core.product')),
            ],
            options={
                'verbose_name': 'Rail Kit',
                'verbose_name_plural': 'Rail Kits',
            },
        ),
    ]
