# Generated by Django 6.0.3 on 2026-04-28 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_railkit'),
        ('core', '0003_alter_product_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('oem_model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('rpm', models.CharField(blank=True, max_length=20, null=True)),
                ('interface', models.CharField(blank=True, choices=[('SAS', 'SAS'), ('SATA', 'SATA'), ('FC', 'FC'), ('NVMe', 'NVMe')], max_length=10, null=True)),
                ('size', models.CharField(blank=True, choices=[('2.5', '2.5 inch'), ('3.5', '3.5 inch')], max_length=5, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_fru_1', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_fru_2', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_fru_3', models.CharField(blank=True, max_length=100, null=True)),
                ('retail_part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('spare_part_tray', models.CharField(blank=True, max_length=100, null=True)),
                ('gpn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('oem_serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware', models.CharField(blank=True, max_length=50, null=True)),
                ('health', models.CharField(blank=True, max_length=20, null=True)),
                ('gb_s', models.CharField(blank=True, max_length=20, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('tray_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harddisk', to='core.product')),
            ],
            options={
                'verbose_name': 'Hard Disk',
                'verbose_name_plural': 'Hard Disks',
            },
        ),
    ]
