# Generated by Django 5.0.6 on 2026-06-03 08:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_card_barcode_alter_controller_barcode_and_more'),
        ('core', '0004_brand_created_at_sparecategory_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='controller',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='cpu',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='harddisk',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='memory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='railkit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='sfp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='spare',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(choices=[('battery', 'Battery'), ('card', 'Card'), ('controller', 'Controller'), ('cpu', 'CPU'), ('harddisk', 'Hard Disk'), ('memory', 'Memory'), ('networking_spare', 'Networking Spare'), ('railkit', 'Rail Kit'), ('server', 'Server'), ('sfp', 'SFP')], max_length=50)),
                ('upload', models.FileField(upload_to='imports/')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkingSpare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('specs', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='networking_spare', to='core.product')),
            ],
            options={
                'verbose_name': 'Networking Spare',
                'verbose_name_plural': 'Networking Spares',
            },
        ),
    ]
