# Generated by Django 5.0.6 on 2026-06-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_card_created_at_controller_created_at_cpu_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='model_key',
            field=models.CharField(choices=[('battery', 'Battery'), ('card', 'Card'), ('controller', 'Controller'), ('cpu', 'CPU'), ('harddisk', 'Hard Disk'), ('memory', 'Memory'), ('networking_spare', 'Networking Spare'), ('railkit', 'Rail Kit'), ('server', 'Server'), ('sfp', 'SFP'), ('stock_out', 'Stock Out')], max_length=50),
        ),
    ]
