# Generated by Django 6.0.3 on 2026-07-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_alter_importjob_model_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='interface',
            field=models.CharField(blank=True, choices=[('SAS', 'SAS'), ('SATA', 'SATA'), ('FC', 'FC'), ('SCSI', 'SCSI')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='harddisk',
            name='interface',
            field=models.CharField(blank=True, choices=[('SAS', 'SAS'), ('SATA', 'SATA'), ('FC', 'FC'), ('NVMe', 'NVMe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='harddisk',
            name='size',
            field=models.CharField(blank=True, choices=[('2.5', '2.5 inch'), ('3.5', '3.5 inch')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='railkit',
            name='side',
            field=models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('PAIR', 'Pair')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sfp',
            name='fibre_type',
            field=models.CharField(blank=True, choices=[('SMF', 'SMF - Single Mode Fibre'), ('MMF', 'MMF - Multi Mode Fibre')], max_length=100, null=True),
        ),
    ]
