# Generated by Django 6.0.3 on 2026-08-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_alter_card_interface_alter_harddisk_interface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='store_location',
            field=models.CharField(default='WH1', max_length=50),
        ),
    ]
