# Generated by Django 6.0.3 on 2026-09-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_importjob_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='harddisk',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
