# Generated by Django 6.0.3 on 2026-03-26 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sparecategory',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_serial__d7777a_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_categor_784c92_idx',
        ),
        migrations.RemoveField(
            model_name='sparecategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='sparecategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sparecategory',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sparecategory'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
