# Generated by Django 6.0.3 on 2026-04-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
