# Generated by Django 5.0.6 on 2026-06-26 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brand_created_at_sparecategory_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('module', models.CharField(choices=[('INVENTORY', 'Inventory'), ('AUDIT', 'Audit'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('USER', 'User'), ('SERVER', 'Server'), ('CONTROLLER', 'Controller'), ('SYSTEM', 'System')], db_index=True, max_length=20)),
                ('entity', models.CharField(blank=True, db_index=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('warehouse', models.CharField(blank=True, db_index=True, max_length=100)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('AUDIT', 'Audit'), ('IMPORT', 'Import'), ('MAP', 'Mapping'), ('UNMAP', 'Unmapping'), ('FREEZE', 'Freeze'), ('UNFREEZE', 'Unfreeze'), ('TRANSFER', 'Transfer')], db_index=True, max_length=20)),
                ('warehouse', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='core.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STOCK_IN', 'Stock In User'), ('STOCK_OUT', 'Stock Out User'), ('AUDIT', 'Audit User')], default='ADMIN', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
