# Generated by Django 5.0.6 on 2026-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettimelineevent',
            name='event_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('AUDIT', 'Audit'), ('IMPORT', 'Import'), ('MAP', 'Mapping'), ('UNMAP', 'Unmapping'), ('FREEZE', 'Freeze'), ('UNFREEZE', 'Unfreeze'), ('TRANSFER', 'Transfer'), ('RETURN', 'Sales Return')], db_index=True, max_length=20),
        ),
    ]
