# Generated by Django 6.0.3 on 2026-09-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettimelineevent',
            name='event_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('AUDIT', 'Audit'), ('IMPORT', 'Import'), ('MAP', 'Mapping'), ('UNMAP', 'Unmapping'), ('FREEZE', 'Freeze'), ('UNFREEZE', 'Unfreeze'), ('TRANSFER', 'Transfer'), ('RETURN', 'Sales Return'), ('STATUS', 'Status Update')], db_index=True, max_length=20),
        ),
    ]
