# Generated by Django 6.0.3 on 2026-09-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_assettimelineevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('kind', models.CharField(choices=[('DAILY_REPORT', 'Daily inventory report (Excel files)'), ('FAILURE_ALERT', 'Failure alerts (import / nightly job errors)')], default='DAILY_REPORT', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to pause without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report recipient',
                'ordering': ['kind', 'email'],
                'unique_together': {('email', 'kind')},
            },
        ),
    ]
