# Generated by Django 4.0.4 on 2026-10-01 11:47

from django.db import migrations, models


def grant_view_live(apps, schema_editor):
    # Live lists now need the 'view_live' permission. Roles that were already
    # customised in Role Settings could see live lists before, so keep that.
    RolePermission = apps.get_model('core', 'RolePermission')
    for row in RolePermission.objects.exclude(role='READONLY_OUT'):
        perms = list(row.permissions or [])
        if 'view_live' not in perms:
            perms.append('view_live')
            row.permissions = perms
            row.save(update_fields=['permissions'])


def revoke_view_live(apps, schema_editor):
    RolePermission = apps.get_model('core', 'RolePermission')
    for row in RolePermission.objects.all():
        perms = [p for p in (row.permissions or []) if p != 'view_live']
        if perms != list(row.permissions or []):
            row.permissions = perms
            row.save(update_fields=['permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_report_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STOCK_IN', 'Stock In User'), ('STOCK_OUT', 'Stock Out User'), ('AUDIT', 'Audit User'), ('READONLY_LIVE', 'Read-only: Live Stock'), ('READONLY_OUT', 'Read-only: Out Stock')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STOCK_IN', 'Stock In User'), ('STOCK_OUT', 'Stock Out User'), ('AUDIT', 'Audit User'), ('READONLY_LIVE', 'Read-only: Live Stock'), ('READONLY_OUT', 'Read-only: Out Stock')], default='ADMIN', max_length=20),
        ),
        migrations.RunPython(grant_view_live, revoke_view_live),
    ]
