# Generated by Django 6.0.3 on 2026-10-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_readonly_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='ADMIN', max_length=40),
        ),
    ]
