from django.urls import path
from . import views

urlpatterns = [
    path('stock-out/', views.stock_out, name='stock_out'),
    path('sales-return/', views.sales_return, name='sales_return'),
    path('scrap-faulty/', views.scrap_faulty_stock, name='scrap_faulty_stock'),
    path('sales-returns/', views.sales_return_history, name='sales_return_history'),
    path('stock-out-status/<str:status>/', views.stock_out_status_list, name='stock_out_status_list'),
    path('audit/', views.audit_spare, name='audit_spare'),
    path('audit-history/<int:product_id>/', views.audit_history, name='audit_history'),
    path('audit-report/', views.audit_report, name='audit_report'),
    path('check-membership/', views.check_product_membership, name='check_product_membership'),
    path('transfer/', views.transfer_inventory, name='transfer_inventory'),
    path('transfer-history/', views.transfer_history, name='transfer_history'),
    path('transfer-requests/', views.transfer_request_page, name='transfer_request_page'),
    path('transfer-requests/create/', views.create_transfer_request, name='create_transfer_request'),
    path('transfer-requests/<int:request_id>/receive/', views.receive_transfer_request, name='receive_transfer_request'),
    path('transfer-requests/<int:request_id>/items/<int:item_id>/receive/', views.receive_transfer_item, name='receive_transfer_item'),
    path('freeze/', views.freeze_inventory, name='freeze_inventory'),
    path('unfreeze/', views.unfreeze_inventory, name='unfreeze_inventory'),
    path('frozen/', views.frozen_inventory_list, name='frozen_inventory_list'),
    path('audit-findings/', views.audit_finding_list, name='audit_finding_list'),
    path('audit-findings/create/', views.create_audit_finding, name='create_audit_finding'),
    path('general-audit-findings/', views.general_audit_finding_list, name='general_audit_finding_list'),
    path('general-audit-findings/create/', views.create_general_audit_finding, name='create_general_audit_finding'),
    path('general-audit-findings/<int:finding_id>/attend/', views.attend_general_audit_finding, name='attend_general_audit_finding'),
    path('activity/', views.activity_trail, name='activity_trail'),
    path('asset-ledger/<int:product_id>/', views.asset_movement_ledger, name='asset_movement_ledger'),
    path('reconciliation/', views.audit_reconciliation, name='audit_reconciliation'),
    path('reconciliation/error-report/', views.reconciliation_error_report, name='reconciliation_error_report'),
    path('map/', views.map_inventory, name='map_inventory'),
    path('unmap/', views.unmap_inventory, name='unmap_inventory'),
    path('map/targets/', views.mapping_targets, name='mapping_targets'),
    path('map/status/', views.mapping_status, name='mapping_status'),
    path('map/history/', views.mapping_history, name='mapping_history'),
    path('rentals/', views.rental_list, name='rental_list'),
    path('rentals/return/', views.return_rental, name='return_rental'),
]
