# Generated by Django 6.0.3 on 2026-05-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_product_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(blank=True, choices=[('RACK SERVER', 'Rack Server'), ('TOWER SERVER', 'Tower Server'), ('BLADE SERVER', 'Blade Server'), ('STORAGE', 'Storage'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('service_tag', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('testing_date', models.DateField(blank=True, null=True)),
                ('tested_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('WORKING', 'Working'), ('NOT WORKING', 'Not Working'), ('PARTIAL', 'Partial'), ('SCRAPPED', 'Scrapped')], default='WORKING', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_location', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_child_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server', to='core.product')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_type', models.CharField(blank=True, max_length=100, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('specs', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('working_status', models.CharField(default='WORKING', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_location', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_child_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_component', to='core.product')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='servers.server')),
            ],
            options={
                'unique_together': {('server', 'product')},
            },
        ),
    ]
