# Generated by Django 5.0.6 on 2026-06-03 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_alt_part_no_server_alt_serial_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servercomponent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
