# Generated by Django 6.0.3 on 2026-10-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_servercomponent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='group',
            field=models.CharField(blank=True, choices=[('blade_server', 'Blade Server'), ('cisco_chassis', 'Cisco Chassis'), ('desktop', 'Desktop'), ('hp_ibm_dell_chassis', 'HP-IBM-DELL Chassis'), ('rack_server', 'Rack Server'), ('storage', 'Storage'), ('sun_servers', 'Sun Servers'), ('networking_firewall', 'Networking Firewall'), ('networking_router_modem', 'Networking Router & Modem'), ('networking_switch', 'Networking Switch')], db_index=True, default='', max_length=40),
        ),
    ]
