# Generated by Django 6.0.3 on 2026-10-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_backfill_server_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='service_tag_missing',
            field=models.BooleanField(default=False),
        ),
    ]
