# Generated by Django 6.0.3 on 2026-03-26 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_brand_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('AUDIT', 'Audit')], max_length=10)),
                ('store_location', models.CharField(choices=[('WH1', 'WH1'), ('WH2', 'WH2'), ('DELHI', 'Delhi'), ('BANGALORE', 'Bangalore'), ('HYDERABAD', 'Hyderabad'), ('CHENNAI', 'Chennai'), ('KOLKATA', 'Kolkata')], max_length=50)),
                ('stock_status', models.CharField(choices=[('SALE', 'Sale'), ('TESTING', 'Testing'), ('RENT', 'Rent'), ('FAULTY', 'Faulty'), ('REPLACEMENT', 'Replacement'), ('ADV_REPLACEMENT', 'Adv Replacement'), ('ON_APPROVAL', 'On Approval'), ('EMPTY', 'Empty'), ('REFILL', 'Refill'), ('SCRAP', 'Scrap')], max_length=50)),
                ('stock_in_date', models.DateField(blank=True, null=True)),
                ('stock_out_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('audited_on', models.DateField(blank=True, null=True)),
                ('audit_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
