# Generated by Django 6.0.3 on 2026-03-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='stock_status',
            field=models.CharField(choices=[('SALE', 'Sale'), ('TESTING', 'Testing'), ('RENT', 'Rent'), ('FAULTY', 'Faulty'), ('REPLACEMENT', 'Replacement'), ('ADV_REPLACEMENT', 'Adv Replacement'), ('ON_APPROVAL', 'On Approval'), ('EMPTY', 'Empty'), ('REFILL', 'Refill'), ('SCRAP', 'Scrap'), ('LIVE', 'Live')], max_length=50),
        ),
    ]
