# Generated by Django 5.0.6 on 2026-06-26 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
        ('inventory', '0004_inventorytransaction_audit_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField()),
                ('remarks', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='audit_findings/')),
                ('person_involved', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-audit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralAuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='general_audit_findings/')),
                ('person', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ATTENDED', 'Attended')], default='OPEN', max_length=20)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('attended_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('attended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_general_audit_findings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_audit_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-audit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryFreezeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FROZEN', 'Frozen'), ('UNFROZEN', 'Unfrozen')], default='FROZEN', max_length=20)),
                ('reason', models.TextField()),
                ('frozen_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('unfrozen_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_inventory', to=settings.AUTH_USER_MODEL)),
                ('parent_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_freeze_records', to='core.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_records', to='core.product')),
                ('unfrozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unfrozen_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-frozen_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_warehouse', models.CharField(choices=[('WH1', 'WH1'), ('WH2', 'WH2'), ('DELHI', 'Delhi'), ('BANGALORE', 'Bangalore'), ('HYDERABAD', 'Hyderabad'), ('CHENNAI', 'Chennai'), ('KOLKATA', 'Kolkata')], max_length=50)),
                ('destination_warehouse', models.CharField(choices=[('WH1', 'WH1'), ('WH2', 'WH2'), ('DELHI', 'Delhi'), ('BANGALORE', 'Bangalore'), ('HYDERABAD', 'Hyderabad'), ('CHENNAI', 'Chennai'), ('KOLKATA', 'Kolkata')], max_length=50)),
                ('source_location', models.CharField(blank=True, max_length=255)),
                ('destination_location', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.product')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
