# Generated by Django 5.0.6 on 2026-07-23 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_assettimelineevent_event_type'),
        ('inventory', '0006_rentalrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('NORMAL', 'Normal return'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('disposition', models.CharField(choices=[('LIVE', 'Return to stock'), ('FAULTY', 'Move to faulty stock')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('returned_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='core.product')),
                ('returned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_sales_returns', to=settings.AUTH_USER_MODEL)),
                ('stock_out_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='inventory.inventorytransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_warehouse', models.CharField(choices=[('WH1', 'WH1'), ('WH2', 'WH2'), ('DELHI', 'Delhi'), ('BANGALORE', 'Bangalore'), ('HYDERABAD', 'Hyderabad'), ('CHENNAI', 'Chennai'), ('KOLKATA', 'Kolkata')], max_length=50)),
                ('destination_warehouse', models.CharField(choices=[('WH1', 'WH1'), ('WH2', 'WH2'), ('DELHI', 'Delhi'), ('BANGALORE', 'Bangalore'), ('HYDERABAD', 'Hyderabad'), ('CHENNAI', 'Chennai'), ('KOLKATA', 'Kolkata')], max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending receipt'), ('PARTIAL', 'Partially received'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('source_location', models.CharField(blank=True, max_length=255)),
                ('destination_location', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_request_items', to='core.product')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfer_items', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.transferrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transferrequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'product'), name='unique_transfer_request_product'),
        ),
    ]
