# Generated by Django 5.0.6 on 2026-07-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_salesreturn_transferrequest_transferrequestitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='stock_status',
            field=models.CharField(choices=[('SALE', 'Sale'), ('TESTING', 'Testing'), ('RENT', 'Rent'), ('FAULTY', 'Faulty'), ('DAMAGED', 'Damaged'), ('REPLACEMENT', 'Replacement'), ('ADV_REPLACEMENT', 'Adv Replacement'), ('ON_APPROVAL', 'On Approval'), ('EMPTY', 'Empty'), ('REFILL', 'Refill'), ('SCRAP', 'Scrap'), ('LIVE', 'Live')], max_length=50),
        ),
    ]
