# Generated by Django 6.0.3 on 2026-08-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventorytransaction_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='disposition',
            field=models.CharField(choices=[('LIVE', 'Return to stock'), ('FAULTY', 'Move to faulty stock'), ('SCRAP', 'Move to scrap')], max_length=20),
        ),
    ]
