# Generated by Django 6.0.3 on 2026-08-26 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rolepermission'),
        ('inventory', '0009_alter_salesreturn_disposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generalauditfinding',
            name='attended_attachment',
            field=models.FileField(blank=True, null=True, upload_to='general_audit_findings/attended/'),
        ),
        migrations.AddIndex(
            model_name='inventoryfreezerecord',
            index=models.Index(fields=['product', '-frozen_at'], name='freeze_prod_frozen_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', '-created_at'], name='invtxn_prod_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'transaction_type', '-created_at'], name='invtxn_prod_type_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type', 'stock_status'], name='invtxn_type_status_idx'),
        ),
    ]
